[project]
name = "doc-scanner-automated-receipt-invoice-parser-using-ocr-nlp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["spacy>=3.7.6"]
